name: fast_testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    # We want to run on external PRs, but not on our own internal
    # PRs as they'll be run by the push to the branch.
    #
    # The main trick is described here:
    # https://github.com/Dart-Code/Dart-Code/pull/2375
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      fail-fast: false
      matrix:
        tarantool:
          - '1.10'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '2.8'

    # There are problems with current version of the
    # setup-tarantool action on Ubuntu Jammy (ubuntu-latest or
    # ubuntu-22.04). Use Ubuntu Focal (ubuntu-20.04) until they
    # will be resolved. See [1] for details.
    #
    # [1]: https://github.com/tarantool/setup-tarantool/issues/36
    runs-on: ubuntu-20.04
    steps:
      - name: Install tarantool ${{ matrix.tarantool }}
        uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: ${{ matrix.tarantool }}

      - name: Clone the module
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: tarantoolctl rocks make
      - run: |
          ./test/merger-test.lua
          ./test/hotreload-test.lua
          ./test/gh-29-merger-use-after-free-in-gen-test.lua
