name: Build mergerx module

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        branch: [tsafin/gh-5273-expand-module-api-v4, tsafin/gh-5273-expand-module-api-1.10-v4]

    steps:
      - name: checkout merger
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: checkout tarantool sources
        uses: actions/checkout@v2
        with:
          repository: tarantool/tarantool
          ref: ${{ matrix.branch }}
          path:  tarantool
          fetch-depth: 0
          submodules: recursive

      - name: Create Tarantool build Environment
        shell: bash
        run: |
          mkdir -p $GITHUB_WORKSPACE/tarantool/build
          mkdir -p $GITHUB_WORKSPACE/share

      - name: Install tarantool build prerequisites for Mac
        if: runner.os == 'macOS'
        run: |
          brew install readline icu4c openssl
          brew install autoconf automake libtool
          brew install msgpuck luajit luarocks

      - name: Install tarantool build prerequisites for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y luarocks libmsgpuck-dev libluajit-5.1-dev

        # by some odd reason we can't use
        #   working-directory: $GITHUB_WORKSPACE/tarantool/build
        # syntax - directory is not yet existing before actions 
        # run. So use workaround with cd
      - name: Configure CMake for Tarantool sources
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/tarantool/build
          cmake $GITHUB_WORKSPACE/tarantool -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_DIST=ON -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/share

      - name: Build and install Tarantool
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/tarantool/build
          cmake --build . --config $BUILD_TYPE --target install -- -j
          echo "::set-env name=PATH::$GITHUB_WORKSPACE/share/bin:$PATH"


      - name: luarocks make and pack
        run: |
          tarantoolctl rocks make --server=https://tmonlibs.github.io/rocks TARANTOOL_DIR=$GITHUB_WORKSPACE/share
          tarantoolctl rocks pack mergerx

      - name: publishing linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: mergerx-scm-1.linux-x86_64.rock
          path: mergerx-scm-1.linux-x86_64.rock

      - name: publishing macosx artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: mergerx-scm-1.macosx-x86_64.rock
          path: mergerx-scm-1.macosx-x86_64.rock

      - name: Install modern Gnu Make on MacOSX
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew install make
          echo "::set-env name=PATH::$(brew --prefix)/opt/make/libexec/gnubin:$PATH"

      - name: check examples
        run: |
          TARANTOOL=$GITHUB_WORKSPACE/tarantool/build/src/tarantool make -C examples/chunked_example test
          tarantoolctl rocks install vshard
          TARANTOOL=$GITHUB_WORKSPACE/tarantool/build/src/tarantool make -C examples/chunked_example_fast test
